# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Lucie"
license = "MIT"
licenselink = "https://github.com/janssens/lucie-croissant-2022/blob/master/themes/lucie/LICENSE"
description = ""
homepage = "https://legislatives-2022.lucie-croissant.fr/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Gaetan Janssens"
  homepage = "plopcom.fr"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
